# Generated by Django 4.2.1 on 2023-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='Номер заказа')),
                ('order_date', models.DateField(verbose_name='Дата')),
                ('game_name', models.CharField(max_length=100, verbose_name='Название игры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('status', models.CharField(choices=[('delivered', 'Доставлен'), ('in_progress', 'В работе'), ('canceled', 'Отменен')], max_length=20, verbose_name='Статус заказа')),
            ],
        ),
    ]
