# Generated by Django 4.2.1 on 2023-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='token_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='Токен')),
                ('seller_id', models.IntegerField(verbose_name='ID продавца')),
                ('valid_thru', models.IntegerField(verbose_name='Годен до')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.AddField(
            model_name='orders',
            name='log_pass',
            field=models.CharField(default='0', max_length=80, verbose_name='Логин и пароль'),
        ),
        migrations.AddField(
            model_name='orders',
            name='uni_code',
            field=models.CharField(default='0', max_length=16, verbose_name='Уникальный код'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='game_name',
            field=models.CharField(max_length=50, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(max_length=10, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('delivered', 'Доставлен'), ('in_progress', 'В работе'), ('exception', 'Отменен'), ('complete', 'Выполнено')], max_length=20, verbose_name='Статус заказа'),
        ),
    ]
